//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bare10.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bare10.Localization.AppText", typeof(AppText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10 er et enkelt verktøy for alle som trenger mer trim og vil ha litt drahjelp. Er du sprek og trener systematisk, bør du nok velge en annen app..
        /// </summary>
        public static string about_1_text {
            get {
                return ResourceManager.GetString("about_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvem passer appen best for?.
        /// </summary>
        public static string about_1_title {
            get {
                return ResourceManager.GetString("about_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frisk gange gjør at du puster litt raskere og blir varmere.  Det skal være litt anstrengende å holde en samtale gående. Fysisk form, vekt og andre forhold vil ha stor betydning for hvor raskt du må gå før pulsen går opp. Det viktige er at du kjenner at du må ta i litt. Det kan bety at du ikke får uttelling med ekstrapoeng og når målene hvis du går sakte. Gi deg selv en klapp på skuldra uansett!
        ///NB! For de fleste telefoner så vil målingen fungere best om du har den i lomma..
        /// </summary>
        public static string about_2_text {
            get {
                return ResourceManager.GetString("about_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva er frisk gange?.
        /// </summary>
        public static string about_2_title {
            get {
                return ResourceManager.GetString("about_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi måler din gange ved å la Google Fit samle inn nødvendig data fra telefonens sensorer. Det gjør innsamlingen mer batterieffektiv og nøyaktig..
        /// </summary>
        public static string about_3_text_android {
            get {
                return ResourceManager.GetString("about_3_text_android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi måler din gange ved å la Helse-integrasjonen samle inn nødvendig data fra telefonens sensorer. Det gjør innsamlingen mer batterieffektiv og nøyaktig..
        /// </summary>
        public static string about_3_text_ios {
            get {
                return ResourceManager.GetString("about_3_text_ios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitetsmåling.
        /// </summary>
        public static string about_3_title {
            get {
                return ResourceManager.GetString("about_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den vil derfor ikke gi deg ekstrapoeng for frisk gange når du går oppover  - og ikke uttelling for trapper. Selv om du anstrenger deg, går tempoet gjerne ned i bakker. Ikke bli skuffet om du ikke får registrert frisk gange. Så lenge du kjenner at du tar i, har det effekt..
        /// </summary>
        public static string about_4_text {
            get {
                return ResourceManager.GetString("about_4_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appen måler ikke høydemetre.
        /// </summary>
        public static string about_4_title {
            get {
                return ResourceManager.GetString("about_4_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestasjon.
        /// </summary>
        public static string accessibility_achievement_item_label {
            get {
                return ResourceManager.GetString("accessibility_achievement_item_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historikk.
        /// </summary>
        public static string accessibility_history_button_title {
            get {
                return ResourceManager.GetString("accessibility_history_button_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fremgang mot dagens mål.
        /// </summary>
        public static string accessibility_history_daily_goal_label {
            get {
                return ResourceManager.GetString("accessibility_history_daily_goal_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har gått {0} av {1} minutter frisk gange.
        /// </summary>
        public static string accessibility_history_daily_goal_progress {
            get {
                return ResourceManager.GetString("accessibility_history_daily_goal_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulerer! Du har nådd dagens mål på {0} minutter.
        /// </summary>
        public static string accessibility_history_daily_goal_reached {
            get {
                return ResourceManager.GetString("accessibility_history_daily_goal_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversikt over dagens gange.
        /// </summary>
        public static string accessibility_history_hourly_breakdown_label {
            get {
                return ResourceManager.GetString("accessibility_history_hourly_breakdown_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversikt over siste 30 dagers frisk gange.
        /// </summary>
        public static string accessibility_history_monthly_breakdown_label {
            get {
                return ResourceManager.GetString("accessibility_history_monthly_breakdown_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversikt over denne ukens frisk gange.
        /// </summary>
        public static string accessibility_history_weekly_breakdown_label {
            get {
                return ResourceManager.GetString("accessibility_history_weekly_breakdown_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdig.
        /// </summary>
        public static string accessibility_onboarding_complete_button_text {
            get {
                return ResourceManager.GetString("accessibility_onboarding_complete_button_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har nå satt deg et nytt mål: {0}.
        /// </summary>
        public static string accessibility_set_goal_description {
            get {
                return ResourceManager.GetString("accessibility_set_goal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt mål.
        /// </summary>
        public static string accessibility_set_goal_title {
            get {
                return ResourceManager.GetString("accessibility_set_goal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hei {0}!.
        /// </summary>
        public static string accessibility_welcome_text {
            get {
                return ResourceManager.GetString("accessibility_welcome_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo! Dette gikk jo superbra! Jekker du opp til sølv?.
        /// </summary>
        public static string achievement_5days_unlocked_bronze {
            get {
                return ResourceManager.GetString("achievement_5days_unlocked_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi bøyer oss i støvet. Nå har du virkelig bevist at du kan!.
        /// </summary>
        public static string achievement_5days_unlocked_gold {
            get {
                return ResourceManager.GetString("achievement_5days_unlocked_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heia deg, sier vi bare! Du har noe veldig bra på gang!.
        /// </summary>
        public static string achievement_5days_unlocked_silver {
            get {
                return ResourceManager.GetString("achievement_5days_unlocked_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nå de daglige målene dine i 30 sammenhengende dager..
        /// </summary>
        public static string achievement_daily_goal_achieved_one_month_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_month_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har nådd dine daglige mål hver dag i 30 dager!.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_month_description_achieved {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_month_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastisk! 30 hele dager kroppen din takker deg for! Unn deg en premie!.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_month_health_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_month_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platinaprisen.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_month_title {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_month_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nå dine daglige mål hver dag i ei uke. .
        /// </summary>
        public static string achievement_daily_goal_achieved_one_week_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_week_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har nådd dine daglige mål hver dag i en hel uke!.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_week_description_achieved {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_week_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutiner spiser slapp viljestyrke til frokost! Allerede nå skjer det positive forandringer i kroppen din – og du kjenner kanskje til og med at hodet kjennes litt &quot;lettere&quot;?.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_week_health_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_week_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronsekampen.
        /// </summary>
        public static string achievement_daily_goal_achieved_one_week_title {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_one_week_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er du klar for å nå målene dine i hele tre uker på rad?.
        /// </summary>
        public static string achievement_daily_goal_achieved_three_weeks_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_three_weeks_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd målene dine tre uker på rad!.
        /// </summary>
        public static string achievement_daily_goal_achieved_three_weeks_description_achieved {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_three_weeks_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulerer! Nå er du på et nivå som øker sjansen for at du holder deg frisk og glad! Du gjør deg selv en fantastisk tjeneste!.
        /// </summary>
        public static string achievement_daily_goal_achieved_three_weeks_health_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_three_weeks_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gullkampen.
        /// </summary>
        public static string achievement_daily_goal_achieved_three_weeks_title {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_three_weeks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppnå ditt daglige mål hver dag i to uker.
        /// </summary>
        public static string achievement_daily_goal_achieved_two_weeks_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_two_weeks_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd målene dine hver dag i to uker på rad!.
        /// </summary>
        public static string achievement_daily_goal_achieved_two_weeks_description_achieved {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_two_weeks_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snart er dette like selvsagt som å pusse tenner – og kanskje merker du allerede at dette er noe du har godt av?.
        /// </summary>
        public static string achievement_daily_goal_achieved_two_weeks_health_description {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_two_weeks_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sølvkampen.
        /// </summary>
        public static string achievement_daily_goal_achieved_two_weeks_title {
            get {
                return ResourceManager.GetString("achievement_daily_goal_achieved_two_weeks_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullfør dine første 10 minutter i friskt tempo..
        /// </summary>
        public static string achievement_first_ten_description {
            get {
                return ResourceManager.GetString("achievement_first_ten_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har fullført dine første 10 minutter i friskt tempo!.
        /// </summary>
        public static string achievement_first_ten_description_achieved {
            get {
                return ResourceManager.GetString("achievement_first_ten_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da er du i gang! Hvert eneste minutt er bedre enn ingenting – og hjertet ditt elsker at du får litt puls!.
        /// </summary>
        public static string achievement_first_ten_health_description {
            get {
                return ResourceManager.GetString("achievement_first_ten_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du er i gang.
        /// </summary>
        public static string achievement_first_ten_title {
            get {
                return ResourceManager.GetString("achievement_first_ten_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grattis! Du er i gang – dette kan bli kjempebra!.
        /// </summary>
        public static string achievement_reachedgoal_unlocked_bronze {
            get {
                return ResourceManager.GetString("achievement_reachedgoal_unlocked_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastisk! Du er på god vei mot noe virkelig bra!.
        /// </summary>
        public static string achievement_reachedgoal_unlocked_gold {
            get {
                return ResourceManager.GetString("achievement_reachedgoal_unlocked_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vel blåst! Du er i siget – kanskje merker du forskjell allerede?.
        /// </summary>
        public static string achievement_reachedgoal_unlocked_silver {
            get {
                return ResourceManager.GetString("achievement_reachedgoal_unlocked_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjør deg klar for neste nivå, og legg til 10 minutter til.. .
        /// </summary>
        public static string achievement_set_harder_goal_description {
            get {
                return ResourceManager.GetString("achievement_set_harder_goal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har økt ditt daglige mål!.
        /// </summary>
        public static string achievement_set_harder_goal_description_achieved {
            get {
                return ResourceManager.GetString("achievement_set_harder_goal_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bra innstilling! 10 er bra – 2x10 er dobbelt så bra! Du er på vei mot et nytt og bedre liv!.
        /// </summary>
        public static string achievement_set_harder_goal_health_description {
            get {
                return ResourceManager.GetString("achievement_set_harder_goal_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nye mål.
        /// </summary>
        public static string achievement_set_harder_goal_title {
            get {
                return ResourceManager.GetString("achievement_set_harder_goal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3x10 hver dag i 100 dager.
        /// </summary>
        public static string achievement_thirty_mins_hundred_days_description {
            get {
                return ResourceManager.GetString("achievement_thirty_mins_hundred_days_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd over 30 minutter hver dag i 100 dager!.
        /// </summary>
        public static string achievement_thirty_mins_hundred_days_description_achieved {
            get {
                return ResourceManager.GetString("achievement_thirty_mins_hundred_days_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder du dette nivået sier statistikken at du får flere leveår – og mer futt og funksjon til å leve livet. Du gjør deg selv en fantastisk tjeneste. Kroppen din er “yngre” enn når du startet - kanskje kjenner du det og?.
        /// </summary>
        public static string achievement_thirty_mins_hundred_days_health_description {
            get {
                return ResourceManager.GetString("achievement_thirty_mins_hundred_days_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamantprisen.
        /// </summary>
        public static string achievement_thirty_mins_hundred_days_title {
            get {
                return ResourceManager.GetString("achievement_thirty_mins_hundred_days_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulerer! Dette er bedre enn tran!.
        /// </summary>
        public static string achievement_thirtyminutes_unlocked_bronze {
            get {
                return ResourceManager.GetString("achievement_thirtyminutes_unlocked_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Kong! Dette likner på et nytt og bedre liv!.
        /// </summary>
        public static string achievement_thirtyminutes_unlocked_gold {
            get {
                return ResourceManager.GetString("achievement_thirtyminutes_unlocked_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dra meg baklengs! Du mener alvor!.
        /// </summary>
        public static string achievement_thirtyminutes_unlocked_silver {
            get {
                return ResourceManager.GetString("achievement_thirtyminutes_unlocked_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall 5 på rad:.
        /// </summary>
        public static string achievement_tier_5days_in_a_row {
            get {
                return ResourceManager.GetString("achievement_tier_5days_in_a_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronse.
        /// </summary>
        public static string achievement_tier_bronze {
            get {
                return ResourceManager.GetString("achievement_tier_bronze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dager på rad:.
        /// </summary>
        public static string achievement_tier_days_in_a_row {
            get {
                return ResourceManager.GetString("achievement_tier_days_in_a_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall mål hittil:.
        /// </summary>
        public static string achievement_tier_goals {
            get {
                return ResourceManager.GetString("achievement_tier_goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gull.
        /// </summary>
        public static string achievement_tier_gold {
            get {
                return ResourceManager.GetString("achievement_tier_gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall minutter gått idag:.
        /// </summary>
        public static string achievement_tier_minutes {
            get {
                return ResourceManager.GetString("achievement_tier_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antall ganger:.
        /// </summary>
        public static string achievement_tier_minutes_total {
            get {
                return ResourceManager.GetString("achievement_tier_minutes_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sølv.
        /// </summary>
        public static string achievement_tier_silver {
            get {
                return ResourceManager.GetString("achievement_tier_silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mottatt.
        /// </summary>
        public static string achievement_time_received {
            get {
                return ResourceManager.GetString("achievement_time_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5-Dagerskongen.
        /// </summary>
        public static string achievement_title_5days {
            get {
                return ResourceManager.GetString("achievement_title_5days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppnå ditt daglige mål 5 dager på rad.
        /// </summary>
        public static string achievement_title_5days_description {
            get {
                return ResourceManager.GetString("achievement_title_5days_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd ditt daglige mål 5 dager på rad.
        /// </summary>
        public static string achievement_title_5days_description_completed {
            get {
                return ResourceManager.GetString("achievement_title_5days_description_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helt om dagen.
        /// </summary>
        public static string achievement_title_reachedgoal {
            get {
                return ResourceManager.GetString("achievement_title_reachedgoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oppnå ditt daglige mål.
        /// </summary>
        public static string achievement_title_reachedgoal_description {
            get {
                return ResourceManager.GetString("achievement_title_reachedgoal_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd ditt daglige mål.
        /// </summary>
        public static string achievement_title_reachedgoal_description_completed {
            get {
                return ResourceManager.GetString("achievement_title_reachedgoal_description_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuttsamleren.
        /// </summary>
        public static string achievement_title_thirtyminutes {
            get {
                return ResourceManager.GetString("achievement_title_thirtyminutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå 30 min i løpet av en dag, uansett tempo.
        /// </summary>
        public static string achievement_title_thirtyminutes_description {
            get {
                return ResourceManager.GetString("achievement_title_thirtyminutes_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har fullført 30 min i løpet av en dag, uansett tempo.
        /// </summary>
        public static string achievement_title_thirtyminutes_description_completed {
            get {
                return ResourceManager.GetString("achievement_title_thirtyminutes_description_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2x10 hver dag i to måneder.
        /// </summary>
        public static string achievement_twenty_mins_sixty_days_description {
            get {
                return ResourceManager.GetString("achievement_twenty_mins_sixty_days_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har oppnådd ditt over 20 minutter hver dag i to måneder!.
        /// </summary>
        public static string achievement_twenty_mins_sixty_days_description_achieved {
            get {
                return ResourceManager.GetString("achievement_twenty_mins_sixty_days_description_achieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ofte kommer livet i veien for endringer du ønsker deg. Ikke nå lenger. Du har bevist at du kan lykkes med å stake ut en stø kurs mot bedre helse og trivsel..
        /// </summary>
        public static string achievement_twenty_mins_sixty_days_health_description {
            get {
                return ResourceManager.GetString("achievement_twenty_mins_sixty_days_health_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobbelt gull.
        /// </summary>
        public static string achievement_twenty_mins_sixty_days_title {
            get {
                return ResourceManager.GetString("achievement_twenty_mins_sixty_days_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prestasjoner.
        /// </summary>
        public static string achievements_tab_item_title {
            get {
                return ResourceManager.GetString("achievements_tab_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frisk gange.
        /// </summary>
        public static string brisk_walk {
            get {
                return ResourceManager.GetString("brisk_walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulerer!.
        /// </summary>
        public static string bulletin_achievement_title {
            get {
                return ResourceManager.GetString("bulletin_achievement_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datainnsamlingen startet fra midnatt, så ikke bli overrasket hvis du ser at det allerede har blitt logget noe gange..
        /// </summary>
        public static string bulletin_midnight_explanation_description {
            get {
                return ResourceManager.GetString("bulletin_midnight_explanation_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjon.
        /// </summary>
        public static string bulletin_midnight_explanation_title {
            get {
                return ResourceManager.GetString("bulletin_midnight_explanation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frisk gange gjør at du puster litt raskere og blir varmere. Det skal være anstrengende å holde en samtale gående..
        /// </summary>
        public static string description_brisk_text {
            get {
                return ResourceManager.GetString("description_brisk_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva er frisk gange?.
        /// </summary>
        public static string description_brisk_title {
            get {
                return ResourceManager.GetString("description_brisk_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10 teller alt under 5 km/t som rolig gange. Rolig gange er mye bedre enn ingen gange – så totalt antall minutter har også betydning for helsa di. Kjenner du at pulsen går litt opp skal du gi deg selv en klapp på skuldra selv om appen ikke belønner deg med friske minutter og heiarop..
        /// </summary>
        public static string description_normal_text {
            get {
                return ResourceManager.GetString("description_normal_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva er rolig gange?.
        /// </summary>
        public static string description_normal_title {
            get {
                return ResourceManager.GetString("description_normal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutter frisk gange hver dag, det skal jeg klare!.
        /// </summary>
        public static string goal_1x10_description {
            get {
                return ResourceManager.GetString("goal_1x10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 x 10 min.
        /// </summary>
        public static string goal_1x10_title {
            get {
                return ResourceManager.GetString("goal_1x10_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen sak, 2x10 minutter har jeg inne!.
        /// </summary>
        public static string goal_2x10_description {
            get {
                return ResourceManager.GetString("goal_2x10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 x 10 min.
        /// </summary>
        public static string goal_2x10_title {
            get {
                return ResourceManager.GetString("goal_2x10_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg tar den helt ut, og satser på 3 x 10 minutter!.
        /// </summary>
        public static string goal_3x10_description {
            get {
                return ResourceManager.GetString("goal_3x10_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 x 10 min.
        /// </summary>
        public static string goal_3x10_title {
            get {
                return ResourceManager.GetString("goal_3x10_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Velg mål.
        /// </summary>
        public static string goals_page_confirm_goal {
            get {
                return ResourceManager.GetString("goals_page_confirm_goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett deg et mål!.
        /// </summary>
        public static string goals_page_title {
            get {
                return ResourceManager.GetString("goals_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mål.
        /// </summary>
        public static string goals_tab_item_title {
            get {
                return ResourceManager.GetString("goals_tab_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friske minutter.
        /// </summary>
        public static string history_chart_generic_title {
            get {
                return ResourceManager.GetString("history_chart_generic_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total gange.
        /// </summary>
        public static string history_chart_generic_title_today {
            get {
                return ResourceManager.GetString("history_chart_generic_title_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siste 30 dager.
        /// </summary>
        public static string history_chart_month_title {
            get {
                return ResourceManager.GetString("history_chart_month_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idag.
        /// </summary>
        public static string history_chart_today_title {
            get {
                return ResourceManager.GetString("history_chart_today_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denne uken.
        /// </summary>
        public static string history_chart_week_title {
            get {
                return ResourceManager.GetString("history_chart_week_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvis du har smartwatch - pass på at bluetooth er på.
        /// </summary>
        public static string history_loading_help_item1 {
            get {
                return ResourceManager.GetString("history_loading_help_item1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass på å lade batteriet.
        /// </summary>
        public static string history_loading_help_item2 {
            get {
                return ResourceManager.GetString("history_loading_help_item2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10 henter data fra Google Fitness API. Sørg for at Gå 10 er tillatt å hente data..
        /// </summary>
        public static string history_loading_help_text_android {
            get {
                return ResourceManager.GetString("history_loading_help_text_android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10 henter data fra HealthKit. Sørg for at Gå 10 er tillatt å hente data..
        /// </summary>
        public static string history_loading_help_text_iOS {
            get {
                return ResourceManager.GetString("history_loading_help_text_iOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen registrert gange?.
        /// </summary>
        public static string history_loading_help_title {
            get {
                return ResourceManager.GetString("history_loading_help_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vent litt. Vi henter inn din registrerte aktivitet..
        /// </summary>
        public static string history_loading_message {
            get {
                return ResourceManager.GetString("history_loading_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitet funnet.
        /// </summary>
        public static string history_loading_message_complete {
            get {
                return ResourceManager.GetString("history_loading_message_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklager, vi finner ikke noen aktivitet..
        /// </summary>
        public static string history_loading_message_error {
            get {
                return ResourceManager.GetString("history_loading_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tips.
        /// </summary>
        public static string history_loading_message_error_tips {
            get {
                return ResourceManager.GetString("history_loading_message_error_tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string history_loading_message_label {
            get {
                return ResourceManager.GetString("history_loading_message_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        public static string history_tab_item_title {
            get {
                return ResourceManager.GetString("history_tab_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagens mål er fullført..
        /// </summary>
        public static string history_todays_goal_completed_text {
            get {
                return ResourceManager.GetString("history_todays_goal_completed_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bra jobba {name}!.
        /// </summary>
        public static string history_todays_goal_completed_title {
            get {
                return ResourceManager.GetString("history_todays_goal_completed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagens Mål.
        /// </summary>
        public static string history_todays_goal_title {
            get {
                return ResourceManager.GetString("history_todays_goal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her kommer oversikt over dagens gange etter du har gått litt.
        /// </summary>
        public static string history_todays_graph_fallback {
            get {
                return ResourceManager.GetString("history_todays_graph_fallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dine prestasjoner.
        /// </summary>
        public static string navigation_achievements_title {
            get {
                return ResourceManager.GetString("navigation_achievements_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbake.
        /// </summary>
        public static string navigation_back {
            get {
                return ResourceManager.GetString("navigation_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sett deg et mål!.
        /// </summary>
        public static string navigation_goal_title {
            get {
                return ResourceManager.GetString("navigation_goal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string navigation_profile_title {
            get {
                return ResourceManager.GetString("navigation_profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har klart en ny prestasjon!.
        /// </summary>
        public static string notification_achievement_unlocked {
            get {
                return ResourceManager.GetString("notification_achievement_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har nådd dagens mål!.
        /// </summary>
        public static string notification_goal_reached {
            get {
                return ResourceManager.GetString("notification_goal_reached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du må logge inn i Google Fit for å fortsette å hente gangdata..
        /// </summary>
        public static string notification_google_fit_auth_failed {
            get {
                return ResourceManager.GetString("notification_google_fit_auth_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10.
        /// </summary>
        public static string notification_title {
            get {
                return ResourceManager.GetString("notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornavn eller kallenavn..
        /// </summary>
        public static string onboarding_entry_text {
            get {
                return ResourceManager.GetString("onboarding_entry_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hva kaller vi deg?.
        /// </summary>
        public static string onboarding_entry_title {
            get {
                return ResourceManager.GetString("onboarding_entry_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå 10 minutter i friskt tempo hver dag..
        /// </summary>
        public static string onboarding_first_text {
            get {
                return ResourceManager.GetString("onboarding_first_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gi kroppen din nytt liv!.
        /// </summary>
        public static string onboarding_first_title {
            get {
                return ResourceManager.GetString("onboarding_first_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hvor høy er du?.
        /// </summary>
        public static string onboarding_height_title {
            get {
                return ResourceManager.GetString("onboarding_height_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husk å ta med deg telefonen i lommen!.
        /// </summary>
        public static string onboarding_last_extra_text {
            get {
                return ResourceManager.GetString("onboarding_last_extra_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bare husk å ha mobilen med deg i lomma..
        /// </summary>
        public static string onboarding_last_text {
            get {
                return ResourceManager.GetString("onboarding_last_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flott! Klar, ferdig, GÅ! .
        /// </summary>
        public static string onboarding_last_title {
            get {
                return ResourceManager.GetString("onboarding_last_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du smartklokke, registreres all aktivitet automatisk i appen. .
        /// </summary>
        public static string onboarding_last_watch_text {
            get {
                return ResourceManager.GetString("onboarding_last_watch_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrere anonym statistikk.
        /// </summary>
        public static string onboarding_statistics_accept {
            get {
                return ResourceManager.GetString("onboarding_statistics_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrere aktiviteten din.
        /// </summary>
        public static string onboarding_term_1 {
            get {
                return ResourceManager.GetString("onboarding_term_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gi deg tips og påminnelser.
        /// </summary>
        public static string onboarding_term_2 {
            get {
                return ResourceManager.GetString("onboarding_term_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vite hvor du er.
        /// </summary>
        public static string onboarding_term_3 {
            get {
                return ResourceManager.GetString("onboarding_term_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg godkjenner .
        /// </summary>
        public static string onboarding_terms_accept {
            get {
                return ResourceManager.GetString("onboarding_terms_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vilkårene.
        /// </summary>
        public static string onboarding_terms_accept_terms {
            get {
                return ResourceManager.GetString("onboarding_terms_accept_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå10 trenger tillatelse til å.
        /// </summary>
        public static string onboarding_terms_text {
            get {
                return ResourceManager.GetString("onboarding_terms_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Først….
        /// </summary>
        public static string onboarding_terms_title {
            get {
                return ResourceManager.GetString("onboarding_terms_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Aktivitetsgjenkjenning.
        /// </summary>
        public static string permission_activity_recognition {
            get {
                return ResourceManager.GetString("permission_activity_recognition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Nøyaktig lokasjon.
        /// </summary>
        public static string permission_fine_location {
            get {
                return ResourceManager.GetString("permission_fine_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Google fitness.
        /// </summary>
        public static string permission_google_fitness {
            get {
                return ResourceManager.GetString("permission_google_fitness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Sted - Alltid.
        /// </summary>
        public static string permission_ios_location {
            get {
                return ResourceManager.GetString("permission_ios_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Bevegelse og kondisjon.
        /// </summary>
        public static string permission_ios_motion {
            get {
                return ResourceManager.GetString("permission_ios_motion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi trenger tillatelser for å vise deg dine data.
        /// </summary>
        public static string permission_title {
            get {
                return ResourceManager.GetString("permission_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAVN:.
        /// </summary>
        public static string profile_name_header {
            get {
                return ResourceManager.GetString("profile_name_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om Gå10.
        /// </summary>
        public static string profile_setting_about_title {
            get {
                return ResourceManager.GetString("profile_setting_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appen er levert av.
        /// </summary>
        public static string profile_setting_credit {
            get {
                return ResourceManager.GetString("profile_setting_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er du sikker på at du vil slette ALL tidligere historikk?.
        /// </summary>
        public static string profile_setting_delete_confirm {
            get {
                return ResourceManager.GetString("profile_setting_delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett dine data.
        /// </summary>
        public static string profile_setting_delete_title {
            get {
                return ResourceManager.GetString("profile_setting_delete_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gi tilbakemelding.
        /// </summary>
        public static string profile_setting_give_feedback {
            get {
                return ResourceManager.GetString("profile_setting_give_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi ønsker stadig å forbedre appen. For å kunne oppnå mer nøyaktig målinger ønsker vi at du oppgir høyden din under Profil..
        /// </summary>
        public static string profile_setting_height_request {
            get {
                return ResourceManager.GetString("profile_setting_height_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Høydemåling.
        /// </summary>
        public static string profile_setting_height_request_title {
            get {
                return ResourceManager.GetString("profile_setting_height_request_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha denne slått på, så får du ekstra hjelp til å nå målene dine..
        /// </summary>
        public static string profile_setting_notification_description {
            get {
                return ResourceManager.GetString("profile_setting_notification_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Få meldinger fra Gå 10.
        /// </summary>
        public static string profile_setting_notification_title {
            get {
                return ResourceManager.GetString("profile_setting_notification_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonym statistikk bidrar til å forbedre tjenesten..
        /// </summary>
        public static string profile_setting_statistics_description {
            get {
                return ResourceManager.GetString("profile_setting_statistics_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrer statistikk.
        /// </summary>
        public static string profile_setting_statistics_title {
            get {
                return ResourceManager.GetString("profile_setting_statistics_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vilkår.
        /// </summary>
        public static string profile_setting_terms_title {
            get {
                return ResourceManager.GetString("profile_setting_terms_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string profile_tab_item_title {
            get {
                return ResourceManager.GetString("profile_tab_item_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolig gange.
        /// </summary>
        public static string regular_walk {
            get {
                return ResourceManager.GetString("regular_walk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del din fremgang.
        /// </summary>
        public static string sharing_dialog_title {
            get {
                return ResourceManager.GetString("sharing_dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeg har gått {0} friske og {1} normale minutter i dag!.
        /// </summary>
        public static string sharing_history_content {
            get {
                return ResourceManager.GetString("sharing_history_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gå 10.
        /// </summary>
        public static string sharing_history_title {
            get {
                return ResourceManager.GetString("sharing_history_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://helsedirektoratet.no/.
        /// </summary>
        public static string sharing_url {
            get {
                return ResourceManager.GetString("sharing_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helsedirektoratet
        ///Vitaminveien 4
        ///0485 Oslo.
        /// </summary>
        public static string terms_1_0_text {
            get {
                return ResourceManager.GetString("terms_1_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App-eier (dataeier).
        /// </summary>
        public static string terms_1_0_title {
            get {
                return ResourceManager.GetString("terms_1_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appen registrerer daglige minutter med frisk gange og gange totalt. Din registrerte aktivitet vises sammen med ditt daglige skritt-mål. Du vil motta daglige motivasjonsmeldinger basert på målet du har satt og hvordan du ligger an..
        /// </summary>
        public static string terms_2_0_text {
            get {
                return ResourceManager.GetString("terms_2_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualisering av dine aktivitetsdata.
        /// </summary>
        public static string terms_2_0_title {
            get {
                return ResourceManager.GetString("terms_2_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Som de fleste apper har vi informasjonskapsler. Formålet er å kunne gi en bedre brukeropplevelse basert på hvordan appen brukes. Vi sparer ikke på andre data enn det du selv har gitt (fornavn). Det er ingen personlige data lagret i appen. I tillegg benytter vi informasjonskapsler for å effektivisere annonseringen av appen, og måle hvor brukerne kommer fra. Våre data blir ikke delt med andre tredjepartsaktører utover det vi beskriver under.
        ///
        ///For å analysere bruken av appen benytter vi oss av ulike analysev [rest of string was truncated]&quot;;.
        /// </summary>
        public static string terms_3_0_text {
            get {
                return ResourceManager.GetString("terms_3_0_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informasjonskapsler.
        /// </summary>
        public static string terms_3_0_title {
            get {
                return ResourceManager.GetString("terms_3_0_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi benytter AppCenter (https://appcenter.ms) for å måle hvilke deler av appen som brukes. Vi bruker denne innsikten til å oppgradere appen for å gi brukeren et bedre verktøy..
        /// </summary>
        public static string terms_3_1_text {
            get {
                return ResourceManager.GetString("terms_3_1_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appsenter.
        /// </summary>
        public static string terms_3_1_title {
            get {
                return ResourceManager.GetString("terms_3_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adform (https://adform.com) er et annonsestyringsverktøy vi bruker for å promotere appen og som gir oss innsikt i hvor brukeren kommer fra..
        /// </summary>
        public static string terms_3_2_text {
            get {
                return ResourceManager.GetString("terms_3_2_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adform.
        /// </summary>
        public static string terms_3_2_title {
            get {
                return ResourceManager.GetString("terms_3_2_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi promoterer appen gjennom Facebook. På samme måte som Adform gir Facebook analytics oss innsikt i bruken og nedlasting av appen (https://facebook.com/about/privacy)..
        /// </summary>
        public static string terms_3_3_text {
            get {
                return ResourceManager.GetString("terms_3_3_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook analytics.
        /// </summary>
        public static string terms_3_3_title {
            get {
                return ResourceManager.GetString("terms_3_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Har du spørsmål vedrørende personvern eller om denne appen vennligst ta kontakt ved å sende e-post til: &lt;u&gt;xx@epost.no&lt;/u&gt;.
        /// </summary>
        public static string terms_final_text {
            get {
                return ResourceManager.GetString("terms_final_text", resourceCulture);
            }
        }
    }
}
